const INIT_BASE = '@@init';
const PAGE_BASE = '@@page';

const GET_INIT_REQUEST = `${INIT_BASE}/GET_INIT_REQUEST`;
const GET_INIT_SUCCESS = `${INIT_BASE}/GET_INIT_SUCCESS`;
const GET_INIT_FAILURE = `${INIT_BASE}/GET_INIT_FAILURE`;

const GET_PAGE_REQUEST = `${PAGE_BASE}/GET_PAGE_REQUEST`;
const GET_PAGE_SUCCESS = `${PAGE_BASE}/GET_PAGE_SUCCESS`;
const GET_PAGE_FAILURE = `${PAGE_BASE}/GET_PAGE_FAILURE`;

export {
  GET_INIT_SUCCESS,
  GET_INIT_REQUEST,
  GET_INIT_FAILURE,
  GET_PAGE_SUCCESS,
  GET_PAGE_REQUEST,
  GET_PAGE_FAILURE,
};
